function compartmentDataTable = readAsegStatsFile(asegFilePath, kwargs)
%
% compartmentDataTable = readAsegStatsFile(asegFilePath, kwargs)
%
% Reads an aseg.stats file for brain compartment statistics table.
% These are related to a corresponding aseg.mgz file with the actual compartment data.
% Both of these files should be generated by the recon-all binary
% of the FreeSurfer software suite.
%

    arguments
        asegFilePath (1,1) string { mustBeFile }
        kwargs.headerRowPrefix (1,1) string = "# ColHeaders"
        kwargs.rowNPrefix (1,1) string = "# NRows"
        kwargs.columnNPrefix (1,1) string = "# NTableCols"
        kwargs.statsFileCommentStyle (1,1) string = "#"
        kwargs.compartmentNameColumnTitle (1,1) string = "StructName"
    end

    % Validate file extension
    if ~ endsWith(asegFilePath, ".stats")
        warning("The given path " + asegFilePath + " did not have the .stats suffix. Are you sure this is the right file?");
    end % if

    % Read the file into a MATLAB table, treating lines starting with '#' as comments
    compartmentDataTable = readtable(asegFilePath, FileType="text", CommentStyle=kwargs.statsFileCommentStyle);

    % Read all lines to parse header information from commented lines
    statsFileLines = readlines(asegFilePath, EmptyLineRule="skip", WhiteSpaceRule="trim");

    lineN = numel(statsFileLines);
    columnN = 0;  % Number of columns in the table
    rowN = 0;     % Number of data rows

    % Parse commented header lines to extract metadata
    for ii = 1 : lineN
        line = statsFileLines(ii);

        % Stop when we reach non-comment lines (data section)
        if ~ startsWith(line, "#")
            break;
        end % if

        % Extract number of columns from header comment
        if startsWith(line, kwargs.columnNPrefix)
            splitLine = split(line);
            columnN = double(splitLine(end));
        end % if

        % Extract number of rows from header comment
        if startsWith(line, kwargs.rowNPrefix)
            splitLine = split(line);
            rowN = double(splitLine(end));
        end % if

        % Extract column headers and assign them to the table
        if startsWith(line, kwargs.headerRowPrefix)
            tableHeaders = split(line);
            % Extract the last 'columnN' elements as column names
            compartmentDataTable.Properties.VariableNames = tableHeaders(end - columnN + 1 : end);
            break;  % Found headers, no need to continue
        end % if

    end % for

    % Convert compartment name column to string type for easier manipulation
    if ismember(kwargs.compartmentNameColumnTitle, compartmentDataTable.Properties.VariableNames)
        compartmentDataTable = convertvars(compartmentDataTable, kwargs.compartmentNameColumnTitle, "string");
    end % if

end % function
