function zeffiro_setup ( kwargs )
%ZEFFIRO_SETUP  Clone optional git submodules and write zef_start_config.m.
%
%   Zeffiro Interface.
%   Copyright © 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   Reads .gitmodules, optionally runs git submodule update for the named
%   packages under external/, and writes src/app/zef_start_config.m so a
%   later zeffiro_interface session can addpath those trees and run their
%   startup scripts. Called from zeffiro_interface and zeffiro_downloader.
%
%   zeffiro_setup
%   zeffiro_setup(Name, Value, ...)
%
%   Name-value arguments
%     submodules       - string column of submodule names from .gitmodules,
%                        or "all". Matching is case-insensitive. Default is
%                        empty (no packages cloned, but the config file is
%                        still opened for write unless skip_submodules).
%     init             - logical, default true. Pass --init to git.
%     remote           - logical, default true. Pass --remote to git.
%     recursive        - logical, default true. Pass --recursive to git.
%     skip_submodules  - logical, default false. Write an empty config
%                        (warning off/on only) and return without git.
%
%   Side effects
%     Overwrites src/app/zef_start_config.m. Runs git submodule update,
%     which mutates external/. The generated config addpath's each cloned
%     submodule when zef.zeffiro_restart is 0, and run()'s a startupscript
%     when .gitmodules defines one that exists on disk.
%
%   Failure
%     Errors if a requested name is not in .gitmodules (plus "all").
%     Errors if the config file cannot be opened for write.
%     Errors with a Git-not-found message on system() status 127.
%     Non-zero git status other than 127 is printed to stderr and skipped.
%
%   See also zeffiro_interface, utilities.io.read_gitmodules.

arguments
    kwargs.submodules (:,1) string = string ( [] )
    kwargs.init (1,1) logical = true
    kwargs.remote (1,1) logical = true
    kwargs.recursive (1,1) logical = true
    kwargs.skip_submodules (1,1) logical = false
end

[this_folder, ~, ~] = fileparts ( mfilename ( "fullpath" ) ) ;

% Validate kwargs.submodules, as this cannot be done in the arguments
% block without writing a validator function.

lower_submodule_names = unique ( lower ( kwargs.submodules ) ) ;

gitmodules_file = fullfile ( this_folder, ".gitmodules" ) ;

submodule_structs = utilities.io.read_gitmodules ( gitmodules_file ) ;

allowed_names = [ submodule_structs.name ] ;

if isrow ( allowed_names )
    allowed_names = transpose ( allowed_names ) ;
end

allowed_names = [ allowed_names ; "all" ] ;

lower_allowed_names = lower ( allowed_names ) ;

if not ( all ( ismember ( lower_submodule_names, lower_allowed_names ) ) )
    error ( ...
        "All of the given Git submodule names (" ...
        + strjoin (lower_submodule_names, ", ") ...
        + ") do not match with the acceptable ones. " ...
        + "The following ones are accepted:" ...
        + newline + newline ...
        + "  " ...
        + strjoin ( lower_allowed_names, newline + "  " ) ...
    ) ;
end

%% Set up path variables.

mfolder = fullfile ( this_folder, "src", "app" ) ;

start_config = fullfile ( mfolder, "zef_start_config.m" ) ;

zeffiro_start_config_fid = fopen ( start_config, 'w' );

if zeffiro_start_config_fid == -1
    error ( ...
        "zeffiro_setup:CannotWriteConfig", ...
        "Could not open ''%s'' for writing. " ...
        + "The file lives under src/app. Make the Zeffiro root writable, e.g. chmod -R u+w .", ...
        start_config ...
    ) ;
end

%% Make sure zef_start_config is closed even in the case of an error or an early return.

cleanup_obj = onCleanup( @() cleanup_fn ( zeffiro_start_config_fid ) ) ;

fprintf(zeffiro_start_config_fid, "%%ZEF_START_CONFIG  Generated by zeffiro_setup. Do not edit.\n");
fprintf(zeffiro_start_config_fid, "%% Regenerated whenever zeffiro_setup runs.\n");
fprintf(zeffiro_start_config_fid, "%% addpath lines for cloned external/ submodules when zef.zeffiro_restart is 0.\n");
fprintf(zeffiro_start_config_fid, "warning off;");

%% Return early if asked to.

if kwargs.skip_submodules
    return
end

%% Start installation of individual packages.

% Set Git submodule cloning settings.

if kwargs.init
    init = " --init" ;
else
    init = "" ;
end

if kwargs.remote
    remote = " --remote" ;
else
    remote = "" ;
end

if kwargs.recursive
    recursive = " --recursive" ;
else
    recursive = "" ;
end

% Determine which set to iterate over, all or just user-provided.

if ismember ( "all", lower_submodule_names )

    iterable = allowed_names (1:end-1) ; % Remove "all"

else

    iterable = kwargs.submodules ;

end

% Clone submodules.

stdout = 1 ;
stderr = 2 ;

for ii = 1 : numel ( iterable )

    lower_submodule_name = lower ( iterable ( ii ) ) ;

    % Find the path corresponding to the name under observation.

    name_ind = find ( lower_allowed_names == lower_submodule_name ) ;

    submodule = submodule_structs ( name_ind ) ;

    [status, message] = system ( "git submodule update" + init + remote + recursive + " " + submodule.path, "-echo" ) ;

    if status == 127

        error ( ...
            "Got exit code of " + status + " when trying to run Git." ...
            + newline ...
            + "This most likely means that Git is not properly installed on your system." ...
            + newline ...
            + " Make sure that the program is both present on your computer, and " ...
            + newline ...
            + "that it has been added to the program search path of the system." ...
        ) ;

    end

    if status ~= 0

        fprintf ( ...
            stderr, ...
            newline ...
            + "Encountered a (possible) issue when cloning submodules with an exit code of " ...
            + status ...
            + ". The output message was as follows:" ...
            + newline + newline ...
            + message ...
        ) ;

        continue

    end

    fprintf ( ...
        zeffiro_start_config_fid, ...
        newline + "if isequal(zef.zeffiro_restart, 0), addpath('" + submodule.path + "'); end;" ...
    ) ;

    if not ( isempty ( submodule.startupscript ) )

        startup_script = fullfile ( this_folder, strtrim ( submodule.startupscript ) ) ;

        if isfile ( startup_script )

            fprintf ( ...
                zeffiro_start_config_fid, ...
                newline + "run ( '" + submodule.startupscript + "' ) ;" ...
            ) ;

        end % if

    end % if

end % for

end % function

%%%%%%%%%%%%%%% Helper functions %%%%%%%%%%%%%%%

function cleanup_fn ( fid )
    % Only write/close if we have a valid file id (fopen returns -1 on failure).
    % Avoids "Invalid file identifier" in destructor when run on read-only trees
    % or when fopen failed (e.g. on some Linux/Ubuntu setups).
    if isempty ( fid ) || fid == -1
        return
    end
    try
        fprintf ( fid, newline + "warning on;" );
        fprintf ( fid, newline );
        fclose ( fid );
    catch
        % Ignore errors during cleanup so onCleanup does not throw
        try
            fclose ( fid );
        catch
            % ignore
        end
    end
end % function
