function zef = zef_update_fss_legacy(zef)
%ZEF_UPDATE_FSS_LEGACY  Ten widgets → zef.inv_synth_source; unit-normalize ori.
%
%   Zeffiro Interface.
%   Copyright © 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   zef = zef_update_fss_legacy(zef)
%
%   Called from Plot source(s) and Create synthetic data. Columns:
%   xyz, ori, amplitude, noise, visual size, color. Does not project
%   through L.
%
%   See also zef_find_source_legacy, zef_init_fss_legacy.

zef.inv_synth_source = str2num(get(zef.h_inv_synth_source_1 ,'string'));
zef.inv_synth_source = zef.inv_synth_source(:);
zef.inv_synth_source = [ zef.inv_synth_source ...
    reshape(str2num(get(zef.h_inv_synth_source_2 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
    reshape(str2num(get(zef.h_inv_synth_source_3 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
    reshape(str2num(get(zef.h_inv_synth_source_4 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
    reshape(str2num(get(zef.h_inv_synth_source_5 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
    reshape(str2num(get(zef.h_inv_synth_source_6 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
    reshape(str2num(get(zef.h_inv_synth_source_7 ,'string')),size(zef.inv_synth_source,1),size(zef.inv_synth_source,2)) ...
    repmat(str2num(get(zef.h_inv_synth_source_8 ,'string')),size(zef.inv_synth_source,1),1) ...
    repmat(str2num(get(zef.h_inv_synth_source_9 ,'string')),size(zef.inv_synth_source,1),1) ...
    repmat(get(zef.h_inv_synth_source_10 ,'value'),size(zef.inv_synth_source,1),1) ...
    ];
zef.inv_synth_source(:,4:6) = zef.inv_synth_source(:,4:6)./repmat(sqrt(sum(zef.inv_synth_source(:,4:6).^2,2)),1,3);

end
