function zef = zef_kalman_class_window(zef)
%ZEF_KALMAN_CLASS_WINDOW  Build the Kalman class-inverter dialog.
%
%   Zeffiro Interface.
%   Copyright 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   See also zef_kalman_class_start, zef_open_class_inverse, inverse.KalmanInverter.

if nargin == 0
    zef = evalin('base', 'zef');
end

spec = struct();
spec.method_id = "kalman";
spec.title = 'Kalman';
spec.method_fields = { ...
    struct('name', 'method_type', 'label', 'Filter type', ...
        'kind', 'dropdown', 'value', 'Basic Kalman filter', ...
        'items', {{'Basic Kalman filter', 'Standardized Kalman filter', ...
            'Approximated Standardized Kalman filter', 'Ensembled Kalman filter'}}, ...
        'scope', 'method'), ...
    struct('name', 'evolution_prior_model', 'label', 'Evolution prior model', ...
        'kind', 'dropdown', 'value', 'Sensitivity scaling', ...
        'items', {{'Sensitivity scaling', 'Avg. sensit. scaling', 'SVD-based', ...
            'Avg. SVD-based', 'Reworked original', 'User supplied Q'}}, ...
        'scope', 'method'), ...
    struct('name', 'number_of_ensembles', 'label', 'Number of ensembles', ...
        'kind', 'numeric', 'value', 100, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'use_smoothing', 'label', 'Use smoothing', ...
        'kind', 'checkbox', 'value', false, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'smoother_type', 'label', 'Smoother type', ...
        'kind', 'dropdown', 'value', 'None', ...
        'items', {{'None', 'RTS', 'Sample RTS'}}, 'scope', 'method'), ...
    struct('name', 'standardization_exponent', 'label', 'Standardization exponent', ...
        'kind', 'numeric', 'value', 0.5, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'evolution_prior_db', 'label', 'Evolution prior (dB)', ...
        'kind', 'numeric', 'value', 0, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'initial_prior_steering_db', 'label', 'Initial prior steering (dB)', ...
        'kind', 'numeric', 'value', 0, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'number_of_noise_steps', 'label', 'Number of noise steps', ...
        'kind', 'numeric', 'value', 4, 'items', {{}}, 'scope', 'method')};

zef = zef_open_class_inverse(zef, spec);

end
