%Copyright © 2024- Sampsa Pursiainen & ZI Development Team
%See: https://github.com/sampsapursiainen/zeffiro_interface
%
%ZEF_DTI_CONDUCTIVITY_WINDOW
%
%Creates the GUI window for DTI Conductivity Tool.
%Uses MATLAB uifigure for modern UI (compatible with R2019a+).
%
%Coordinate transformation matrices (vox2ras, vox2ras-tkr, center) are
%automatically extracted from the input files — no manual matrix entry needed.
%The user only needs to provide:
%  - FA file (fa.nii.gz from dt_recon)
%  - v1 file (v1.nii.gz, optional principal eigenvector)
%  - register.dat (from dt_recon)
%  - Reference MRI (e.g. orig.mgz from recon-all)

function zef = zef_dti_conductivity_window(zef)
% --- Zeffiro documentation header ---
% zef_dti_conductivity_window — Zef dti conductivity window.
%
% Purpose:
%   Zef dti conductivity window.
%   Folder: Individual Zeffiro plugins (inverse GUIs, data bank, Kalman, SESAME, etc.) registered via profile INI files.
%
% Inputs:
%   zef
%
% Outputs:
%   zef
%
% Zef fields (observed):
%   zef.compartment_tags (read)
%   zef.dti_anisotropy_threshold (read, write)
%   zef.dti_apply_to_compartments (read)
%   zef.dti_conductivity_scale (read, write)
%   zef.dti_conductivity_tool_current_size (read, write)
%   zef.dti_conductivity_tool_relative_size (read, write)
%   zef.dti_extra_conductivity (read, write)
%   zef.dti_interpolation_mode (read, write)
%   zef.dti_interpolation_radius (read, write)
%   zef.dti_intra_conductivity (read, write)
%   zef.dti_ref_geometry (read)
%   zef.dti_ref_mri_file (read, write)
%   zef.dti_volume_fraction (read, write)
%   zef.freesurfer_fa_file (read, write)
%   zef.freesurfer_register_file (read, write)
%   … (27 more)
%
% Calls (project):
%   zef_change_size_function
%   zef_dti_conductivity_apply_button_callback
%   zef_dti_conductivity_load_freesurfer
%   zef_dti_conductivity_update_conversion_model
%   zef_dti_conductivity_update_interpolation_model
%   zef_dti_conductivity_window
%   zef_get_relative_size
%
% Side effects:
%   - base/caller workspace
%   - creates/updates figures
%   - reads/updates `zef` struct fields
%
% Workflow:
%   GUI: Invoked from a menu, button, or table callback in the Zeffiro tools.
%   Programmatic: `[zef] = zef_dti_conductivity_window(zef)` with project root and `src` on the path.
% --- End Zeffiro documentation header


if nargin == 0
    zef = evalin('base','zef');
end

% Check if window already exists (with error handling)
if isfield(zef,'h_dti_conductivity_tool')
    try
        if isvalid(zef.h_dti_conductivity_tool)
            figure(zef.h_dti_conductivity_tool);
            return;
        end
    catch
        % Handle is invalid, continue to create new window
        zef.h_dti_conductivity_tool = [];
    end
end

% Create figure using uifigure (modern MATLAB UI)
WINDOW_HEIGHT = 1010;
zef.h_dti_conductivity_tool = uifigure(...
    'Name', 'ZEFFIRO Interface: DTI Conductivity Tool', ...
    'Position', [100 100 675 WINDOW_HEIGHT], ...
    'Visible', 'on', ...
    'Resize', 'on');

% Layout constants for easier maintenance
PANEL_MARGIN = 15;
PANEL_WIDTH = 650;
SPACING = 10;

% Calculate positions from bottom (y=0 is bottom, y=WINDOW_HEIGHT is top)
INFO_PANEL_HEIGHT = 150;
INFO_PANEL_Y = PANEL_MARGIN;
ACTION_BUTTON_HEIGHT = 50;
ACTION_Y = INFO_PANEL_Y + INFO_PANEL_HEIGHT + SPACING;
COMPART_HEIGHT = 135;
COMPART_PANEL_HEIGHT = 180;
COMPART_Y = ACTION_Y + ACTION_BUTTON_HEIGHT + SPACING;
INTERP_PANEL_HEIGHT = 140;
INTERP_PANEL_Y = COMPART_Y + COMPART_HEIGHT + SPACING;
MODEL_PANEL_HEIGHT = 220;
MODEL_PANEL_Y = INTERP_PANEL_Y + INTERP_PANEL_HEIGHT + SPACING;
FILE_PANEL_HEIGHT = 200;
FILE_PANEL_Y = MODEL_PANEL_Y + MODEL_PANEL_HEIGHT + SPACING;
STATUS_HEIGHT = 30;
STATUS_Y = FILE_PANEL_Y + FILE_PANEL_HEIGHT + SPACING;

% ========================================================================
% FILE SELECTION PANEL
% ========================================================================
% WHY: User specifies FreeSurfer files. All coordinate transformation
% matrices are extracted automatically from these files.

uipanel(zef.h_dti_conductivity_tool, ...
    'Title', 'FreeSurfer Input Files', ...
    'Position', [PANEL_MARGIN FILE_PANEL_Y PANEL_WIDTH FILE_PANEL_HEIGHT]);

% Reference MRI File (NEW - e.g. orig.mgz)
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Reference MRI:', ...
    'Position', [PANEL_MARGIN+10 FILE_PANEL_Y+130 100 30]);

zef.h_dti_ref_mri_file = uieditfield(zef.h_dti_conductivity_tool, ...
    'text', ...
    'Position', [PANEL_MARGIN+120 FILE_PANEL_Y+130 300 30], ...
    'Value', '', ...
    'Tooltip', 'FreeSurfer anatomical volume (e.g. orig.mgz) — provides vox2ras, vox2ras-tkr, center', ...
    'ValueChangedFcn', 'zef.dti_ref_mri_file = zef.h_dti_ref_mri_file.Value; assignin(''base'',''zef'',zef);');

zef.h_dti_browse_ref_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Browse...', ...
    'Position', [PANEL_MARGIN+430 FILE_PANEL_Y+130 80 30], ...
    'ButtonPushedFcn', 'zef_dti_conductivity_browse_ref;');

% Reference MRI status label
zef.h_dti_ref_status = uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'No reference MRI loaded', ...
    'Position', [PANEL_MARGIN+120 FILE_PANEL_Y+110 410 20], ...
    'FontSize', 9, ...
    'FontColor', [0.5 0.5 0.5]);

% FreeSurfer FA File
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'FA File (fa.nii.gz):', ...
    'Position', [PANEL_MARGIN+10 FILE_PANEL_Y+80 100 30]);

zef.h_freesurfer_fa_file = uieditfield(zef.h_dti_conductivity_tool, ...
    'text', ...
    'Position', [PANEL_MARGIN+120 FILE_PANEL_Y+80 300 30], ...
    'Value', '', ...
    'ValueChangedFcn', 'zef.freesurfer_fa_file = zef.h_freesurfer_fa_file.Value; assignin(''base'',''zef'',zef);');

zef.h_freesurfer_browse_fa_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Browse...', ...
    'Position', [PANEL_MARGIN+430 FILE_PANEL_Y+80 80 30], ...
    'ButtonPushedFcn', 'zef_dti_conductivity_browse_fa;');

% FreeSurfer v1 File (principal eigenvector, optional but recommended)
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'v1 File (optional):', ...
    'Position', [PANEL_MARGIN+10 FILE_PANEL_Y+45 100 30]);

zef.h_freesurfer_v1_file = uieditfield(zef.h_dti_conductivity_tool, ...
    'text', ...
    'Position', [PANEL_MARGIN+120 FILE_PANEL_Y+45 300 30], ...
    'Value', '', ...
    'ValueChangedFcn', 'zef.freesurfer_v1_file = zef.h_freesurfer_v1_file.Value; assignin(''base'',''zef'',zef);');

zef.h_freesurfer_browse_v1_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Browse...', ...
    'Position', [PANEL_MARGIN+430 FILE_PANEL_Y+45 80 30], ...
    'ButtonPushedFcn', 'zef_dti_conductivity_browse_v1;');

% FreeSurfer register.dat File
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'register.dat:', ...
    'Position', [PANEL_MARGIN+10 FILE_PANEL_Y+10 100 30]);

zef.h_freesurfer_register_file = uieditfield(zef.h_dti_conductivity_tool, ...
    'text', ...
    'Position', [PANEL_MARGIN+120 FILE_PANEL_Y+10 300 30], ...
    'Value', '', ...
    'ValueChangedFcn', 'zef.freesurfer_register_file = zef.h_freesurfer_register_file.Value; assignin(''base'',''zef'',zef);');

zef.h_freesurfer_browse_register_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Browse...', ...
    'Position', [PANEL_MARGIN+430 FILE_PANEL_Y+10 80 30], ...
    'ButtonPushedFcn', 'zef_dti_conductivity_browse_register;');

% Load button (positioned to the right of the panel)
zef.h_dti_load_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Load', ...
    'Position', [PANEL_MARGIN+540 FILE_PANEL_Y+95 100 65], ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', 'zef = zef_dti_conductivity_load_freesurfer(zef); assignin(''base'',''zef'',zef);');

zef.h_dti_clear_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Clear', ...
    'Position', [PANEL_MARGIN+540 FILE_PANEL_Y+10 100 65], ...
    'FontSize', 18, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', 'zef_dti_conductivity_clear;');

% Status (below file panel)
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Status:', ...
    'Position', [PANEL_MARGIN+10 STATUS_Y 100 30]);

zef.h_dti_status_text = uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'No FreeSurfer FA data loaded', ...
    'Position', [PANEL_MARGIN+120 STATUS_Y 650 30], ...
    'FontColor', [0.5 0.5 0.5]);

% ========================================================================
% CONVERSION MODEL PANEL
% ========================================================================
% WHY: User needs to select and configure conversion model
% Models: 1=Volume Fraction, 2=Effective Medium, 3=Direct Scaling

uipanel(zef.h_dti_conductivity_tool, ...
    'Title', 'Conversion Model', ...
    'Position', [PANEL_MARGIN MODEL_PANEL_Y PANEL_WIDTH MODEL_PANEL_HEIGHT]);

% Model selection dropdown
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Model:', ...
    'Position', [PANEL_MARGIN+10 MODEL_PANEL_Y+150 120 30]);

zef.h_dti_model_dropdown = uidropdown(zef.h_dti_conductivity_tool, ...
    'Items', {'Volume Fraction (Tuch et al.)', 'Effective Medium Theory', 'Direct Scaling'}, ...
    'ItemsData', [1, 2, 3], ...
    'Position', [PANEL_MARGIN+120 MODEL_PANEL_Y+150 510 30], ...
    'ValueChangedFcn', 'zef_dti_conductivity_update_model;');

% Row 1: Volume Fraction (for models 1 and 2)
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Volume Fraction:', ...
    'Position', [PANEL_MARGIN+10 MODEL_PANEL_Y+115 130 30]);

zef.h_dti_volume_fraction = uispinner(zef.h_dti_conductivity_tool, ...
    'Limits', [0 1], ...
    'Step', 0.05, ...
    'Position', [PANEL_MARGIN+120 MODEL_PANEL_Y+115 110 30], ...
    'Value', 0.7, ...
    'ValueChangedFcn', 'zef.dti_volume_fraction = zef.h_dti_volume_fraction.Value; assignin(''base'',''zef'',zef);');

% Row 1: Extra conductivity (for models 1 and 2)
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Extra (S/m):', ...
    'Position', [PANEL_MARGIN+250 MODEL_PANEL_Y+115 100 30]);

zef.h_dti_extra_conductivity = uispinner(zef.h_dti_conductivity_tool, ...
    'Limits', [0.01 10], ...
    'Step', 0.1, ...
    'Position', [PANEL_MARGIN+330 MODEL_PANEL_Y+115 110 30], ...
    'Value', 1.0, ...
    'ValueChangedFcn', 'zef.dti_extra_conductivity = zef.h_dti_extra_conductivity.Value; assignin(''base'',''zef'',zef);');

% Row 1: Intra conductivity (for models 1 and 2)
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Intra (S/m):', ...
    'Position', [PANEL_MARGIN+460 MODEL_PANEL_Y+115 100 30]);

zef.h_dti_intra_conductivity = uispinner(zef.h_dti_conductivity_tool, ...
    'Limits', [0.01 10], ...
    'Step', 0.1, ...
    'Position', [PANEL_MARGIN+520 MODEL_PANEL_Y+115 110 30], ...
    'Value', 0.6, ...
    'ValueChangedFcn', 'zef.dti_intra_conductivity = zef.h_dti_intra_conductivity.Value; assignin(''base'',''zef'',zef);');

% Row 2: Scale Factor (for model 3 - Direct Scaling)
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Scale Factor:', ...
    'Position', [PANEL_MARGIN+10 MODEL_PANEL_Y+80 130 30]);

zef.h_dti_conductivity_scale = uispinner(zef.h_dti_conductivity_tool, ...
    'Limits', [0.01 10], ...
    'Step', 0.1, ...
    'Position', [PANEL_MARGIN+120 MODEL_PANEL_Y+80 110 30], ...
    'Value', 1.0, ...
    'ValueChangedFcn', 'zef.dti_conductivity_scale = zef.h_dti_conductivity_scale.Value; assignin(''base'',''zef'',zef);');

% Help text for scale factor
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', '(Direct scaling: sigma = scale * D)', ...
    'Position', [PANEL_MARGIN+250 MODEL_PANEL_Y+80 300 30], ...
    'FontSize', 9, ...
    'FontColor', [0.5 0.5 0.5]);

% Row 3: Anisotropy threshold (for all models, but mainly models 1 and 2)
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Anisotropy Threshold:', ...
    'Position', [PANEL_MARGIN+10 MODEL_PANEL_Y+45 150 30]);

zef.h_dti_anisotropy_threshold = uispinner(zef.h_dti_conductivity_tool, ...
    'Limits', [0 1], ...
    'Step', 0.05, ...
    'Position', [PANEL_MARGIN+120 MODEL_PANEL_Y+45 110 30], ...
    'Value', 0.2, ...
    'ValueChangedFcn', 'zef.dti_anisotropy_threshold = zef.h_dti_anisotropy_threshold.Value; assignin(''base'',''zef'',zef);');

% Help text for anisotropy threshold
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', '(Minimum FA to apply anisotropy, default: 0.2)', ...
    'Position', [PANEL_MARGIN+250 MODEL_PANEL_Y+45 400 30], ...
    'FontSize', 9, ...
    'FontColor', [0.5 0.5 0.5]);

% Update Conversion Model button
zef.h_dti_update_conversion_model_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Update Conversion Model Parameters', ...
    'Position', [PANEL_MARGIN+10 MODEL_PANEL_Y+10 PANEL_WIDTH-20 30], ...
    'FontSize', 15, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', 'zef = zef_dti_conductivity_update_conversion_model(zef); assignin(''base'',''zef'',zef);');

% ========================================================================
% INTERPOLATION PANEL
% ========================================================================
% WHY: Control how DTI maps to mesh

uipanel(zef.h_dti_conductivity_tool, ...
    'Title', 'Interpolation', ...
    'Position', [PANEL_MARGIN INTERP_PANEL_Y PANEL_WIDTH INTERP_PANEL_HEIGHT]);

% Interpolation mode
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Mode:', ...
    'Position', [PANEL_MARGIN+10 INTERP_PANEL_Y+70 80 30]);

zef.h_dti_interp_mode = uidropdown(zef.h_dti_conductivity_tool, ...
    'Items', {'Nearest Neighbor', 'Radius Average'}, ...
    'ItemsData', {'nearest', 'radius_average'}, ...
    'Position', [PANEL_MARGIN+130 INTERP_PANEL_Y+70 150 30], ...
    'ValueChangedFcn', 'zef.dti_interpolation_mode = zef.h_dti_interp_mode.Value; assignin(''base'',''zef'',zef);');

% Interpolation radius
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Radius (mm):', ...
    'Position', [PANEL_MARGIN+360 INTERP_PANEL_Y+70 80 30]);

zef.h_dti_interp_radius = uispinner(zef.h_dti_conductivity_tool, ...
    'Limits', [0.1 10], ...
    'Step', 0.1, ...
    'Position', [PANEL_MARGIN+500 INTERP_PANEL_Y+70 80 30], ...
    'Value', 2.0, ...
    'ValueChangedFcn', 'zef.dti_interpolation_radius = zef.h_dti_interp_radius.Value; assignin(''base'',''zef'',zef);');

% Help text for interpolation
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Radius Average: averages conductivity within radius around each mesh point', ...
    'Position', [PANEL_MARGIN+10 INTERP_PANEL_Y+40 600 30], ...
    'FontSize', 9, ...
    'FontColor', [0.5 0.5 0.5]);

% Update Interpolation Model button
zef.h_dti_update_interpolation_model_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Update Interpolation Model', ...
    'Position', [PANEL_MARGIN+10 INTERP_PANEL_Y+10 PANEL_WIDTH-20 30], ...
    'FontSize', 15, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', 'zef = zef_dti_conductivity_update_interpolation_model(zef); assignin(''base'',''zef'',zef);');

% ========================================================================
% COMPARTMENT SELECTION
% ========================================================================
% WHY: Allow selective application from available compartments

COMPART_PANEL_Y = COMPART_Y - COMPART_PANEL_HEIGHT + COMPART_HEIGHT;
uipanel(zef.h_dti_conductivity_tool, ...
    'Title', 'Compartment Selection', ...
    'Position', [PANEL_MARGIN COMPART_PANEL_Y PANEL_WIDTH COMPART_PANEL_HEIGHT]);

uilabel(zef.h_dti_conductivity_tool, ...
    'Text', 'Apply to compartments:', ...
    'Position', [PANEL_MARGIN+10 COMPART_Y+80 150 30]);

% Build list of compartments with display names
compartment_items = {};
compartment_items_data = {};
try
    if isfield(zef,'compartment_tags') && ~isempty(zef.compartment_tags)
        for k = 1:length(zef.compartment_tags)
            tag = zef.compartment_tags{k};
            % Get compartment name (use name if available, otherwise use tag)
            name_field = [tag '_name'];
            if isfield(zef, name_field) && ~isempty(zef.(name_field))
                comp_name = zef.(name_field);
                % Handle string/cell conversion
                if iscell(comp_name)
                    comp_name = comp_name{1};
                elseif isstring(comp_name)
                    comp_name = char(comp_name);
                end
                % Ensure it's a char array
                if ~ischar(comp_name)
                    comp_name = tag;
                end
            else
                comp_name = tag;
            end
            % Check if compartment is active
            on_field = [tag '_on'];
            if isfield(zef, on_field) && zef.(on_field)
                comp_name = [comp_name ' (active)'];
            else
                comp_name = [comp_name ' (inactive)'];
            end
            compartment_items{end+1} = comp_name;
            compartment_items_data{end+1} = tag;
        end
    else
        compartment_items = {'No compartments available'};
        compartment_items_data = {''};
    end
catch ME
    compartment_items = {'Error loading compartments'};
    compartment_items_data = {''};
end

% Set initial selection based on zef.dti_apply_to_compartments
initial_selection = {};
if isfield(zef,'dti_apply_to_compartments') && ~isempty(zef.dti_apply_to_compartments)
    if ischar(zef.dti_apply_to_compartments) || isstring(zef.dti_apply_to_compartments)
        initial_selection = {char(zef.dti_apply_to_compartments)};
    elseif iscell(zef.dti_apply_to_compartments)
        initial_selection = zef.dti_apply_to_compartments;
    end
    % Filter to only include tags that exist in compartment_items_data
    if ~isempty(initial_selection) && ~isempty(compartment_items_data)
        valid_indices = ismember(initial_selection, compartment_items_data);
        initial_selection = initial_selection(valid_indices);
    end
end

% If no initial selection, default to gray and white matter if available
if isempty(initial_selection) && ~isempty(compartment_items_data)
    default_tags = {'g', 'w'};
    for dt = default_tags
        idx = find(strcmp(compartment_items_data, dt{1}), 1);
        if ~isempty(idx)
            initial_selection{end+1} = dt{1};
        end
    end
end

% Create listbox for compartment selection (multi-select)
zef.h_dti_compartments = uilistbox(zef.h_dti_conductivity_tool, ...
    'Items', compartment_items, ...
    'ItemsData', compartment_items_data, ...
    'Multiselect', 'on', ...
    'Position', [PANEL_MARGIN+140 COMPART_Y-30 320 COMPART_HEIGHT], ...
    'Value', initial_selection, ...
    'ValueChangedFcn', 'zef_dti_conductivity_update_compartments;');

% Help text for compartment selection
uilabel(zef.h_dti_conductivity_tool, ...
    'Text', '(Hold Ctrl/Cmd to select multiple)', ...
    'Position', [PANEL_MARGIN+10 COMPART_Y + 60 270 30], ...
    'FontSize', 9, ...
    'FontColor', [0.5 0.5 0.5]);

% Apply to Mesh button
zef.h_dti_apply_button = uibutton(zef.h_dti_conductivity_tool, ...
    'push', ...
    'Text', 'Apply to Mesh', ...
    'Position', [PANEL_MARGIN+490 COMPART_Y-30 140 COMPART_HEIGHT], ...
    'FontSize', 15, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', 'zef_dti_conductivity_apply_button_callback();');

% ========================================================================
% INFO PANEL
% ========================================================================
% WHY: Show current status and metadata

uipanel(zef.h_dti_conductivity_tool, ...
    'Title', 'Information', ...
    'Position', [PANEL_MARGIN INFO_PANEL_Y PANEL_WIDTH INFO_PANEL_HEIGHT]);

zef.h_dti_info_text = uitextarea(zef.h_dti_conductivity_tool, ...
    'Position', [PANEL_MARGIN+10 INFO_PANEL_Y+10 PANEL_WIDTH-20 INFO_PANEL_HEIGHT-45], ...
    'Editable', 'off', ...
    'Value', {'No FreeSurfer FA data loaded.', '', 'Instructions:', ...
              '1. Select Reference MRI file (e.g. orig.mgz from recon-all output)', ...
              '2. Select FA file (fa.nii.gz from dt_recon output)', ...
              '3. Select register.dat (from dt_recon output directory)', ...
              '4. Click "Load" to import (matrices are auto-extracted)', ...
              '5. Select conversion model and adjust parameters', ...
              '6. Set interpolation mode and radius', ...
              '7. Select compartments to apply DTI conductivity', ...
              '8. Click "Apply to Mesh" to update conductivity', ...
              '', ...
              'Coordinate transformation matrices are automatically extracted', ...
              'from the input files. No manual matrix entry is required.'});

% ========================================================================
% POPULATE GUI FROM EXISTING ZEF VALUES
% ========================================================================

% Reference MRI file path
if isfield(zef,'dti_ref_mri_file') && ~isempty(zef.dti_ref_mri_file)
    zef.h_dti_ref_mri_file.Value = zef.dti_ref_mri_file;
    % Update status if geometry is loaded
    if isfield(zef,'dti_ref_geometry') && ~isempty(zef.dti_ref_geometry)
        rg = zef.dti_ref_geometry;
        zef.h_dti_ref_status.Text = sprintf('Geometry OK: %dx%dx%d, center [%.1f, %.1f, %.1f]', ...
            rg.dimensions(1), rg.dimensions(2), rg.dimensions(3), ...
            rg.center_ras(1), rg.center_ras(2), rg.center_ras(3));
        zef.h_dti_ref_status.FontColor = [0 0.7 0];
    end
end

% FA file path
if isfield(zef,'freesurfer_fa_file') && ~isempty(zef.freesurfer_fa_file)
    zef.h_freesurfer_fa_file.Value = zef.freesurfer_fa_file;
end

% v1 file path
if isfield(zef,'freesurfer_v1_file') && ~isempty(zef.freesurfer_v1_file)
    zef.h_freesurfer_v1_file.Value = zef.freesurfer_v1_file;
end

% Register file path
if isfield(zef,'freesurfer_register_file') && ~isempty(zef.freesurfer_register_file)
    zef.h_freesurfer_register_file.Value = zef.freesurfer_register_file;
end

% ========================================================================
% ENABLE RESPONSIVE RESIZING
% ========================================================================
% WHY: Allow GUI elements to scale with window size changes
% Uses the same resize mechanism as other ZEFFIRO tools

% Disable automatic resizing (we handle it manually)
set(zef.h_dti_conductivity_tool,'AutoResizeChildren','off');

% Store current size for resize calculations
zef.dti_conductivity_tool_current_size = get(zef.h_dti_conductivity_tool,'Position');

% Get relative sizes for all child elements
zef.dti_conductivity_tool_relative_size = zef_get_relative_size(zef.h_dti_conductivity_tool);

% Set up SizeChangedFcn to handle window resizing
% This will scale all child elements proportionally when window is resized
set(zef.h_dti_conductivity_tool,'SizeChangedFcn',...
    'zef.dti_conductivity_tool_current_size = zef_change_size_function(zef.h_dti_conductivity_tool,zef.dti_conductivity_tool_current_size,zef.dti_conductivity_tool_relative_size);');

% Store window handle
if nargout == 0
    assignin('base','zef',zef);
end

end
