function [G, dipole_locations] =  zef_lead_field_interpolation( ...
    p_nodes, ...
    p_tetrahedra, ...
    p_brain_inds, ...
    p_source_model, ...
    p_intended_source_inds, ...
    p_nearest_neighbour_inds, ...
    p_optimization_system_type, ...
    p_regparam ...
    )

%ZEF_LEAD_FIELD_INTERPOLATION  Source-to-column interpolation matrix G.
%
%   Zeffiro Interface.
%   Copyright © 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   Used inside the FEM assemblers (not from the Mesh tool). Maps intended
%   source tetrahedra to nodal columns before the Schur product L = Schur \
%   (T'*G). Dispatches on core.types.ZefSourceModel.from(p_source_model):
%     Whitney / ContinuousWhitney     → zef_whitney_interpolation
%     Hdiv / ContinuousHdiv           → zef_hdiv_interpolation
%     StVenant / ContinuousStVenant   → zef_st_venant_interpolation (uses p_regparam)
%
%   [G, dipole_locations] = zef_lead_field_interpolation( ...
%       p_nodes, p_tetrahedra, p_brain_inds, p_source_model, ...
%       p_intended_source_inds, p_nearest_neighbour_inds, ...
%       p_optimization_system_type, p_regparam)
%
%   Input
%     p_nodes                    - [n_nodes × 3] (metres in the FEM call)
%     p_tetrahedra               - [n_tet × 4] node indices
%     p_brain_inds               - tetra indices allowed as sources
%     p_source_model             - enum, numeric 1–6, or string
%     p_intended_source_inds     - source tetra indices
%     p_nearest_neighbour_inds   - continuous-source neighbours (required by arguments)
%     p_optimization_system_type - 'pbo', 'mpo', or 'none'
%     p_regparam                 - St. Venant regularizer (EEG FEM uses 1e-6)
%
%   Output
%     G                 - sparse [n_nodes × n_source_columns]
%     dipole_locations  - [n × 3] corresponding source points
%
%   See also zef_lead_field_eeg_fem, core.types.ZefSourceModel.


arguments
    p_nodes (:,3) double {mustBeNonNan}
    p_tetrahedra (:,4) double {mustBeInteger, mustBePositive}
    p_brain_inds (:,1) double {mustBeInteger, mustBePositive}
    p_source_model
    p_intended_source_inds (:,1) double {mustBeInteger, mustBePositive}
    p_nearest_neighbour_inds (:,1) double {mustBeInteger, mustBePositive}
    p_optimization_system_type { ...
        mustBeText, ...
        mustBeMember(p_optimization_system_type,{'pbo','mpo','none'}) ...
        }
    p_regparam (1,1) double
end

switch core.types.ZefSourceModel.from(p_source_model)

    case { core.types.ZefSourceModel.Whitney, core.types.ZefSourceModel.ContinuousWhitney }

        [G, dipole_locations] = zef_whitney_interpolation( ...
            p_nodes, ...
            p_tetrahedra, ...
            p_brain_inds, ...
            p_intended_source_inds, ...
            p_nearest_neighbour_inds, ...
            p_optimization_system_type ...
            );

    case { core.types.ZefSourceModel.Hdiv, core.types.ZefSourceModel.ContinuousHdiv }

        [G, dipole_locations] = zef_hdiv_interpolation( ...
            p_nodes, ...
            p_tetrahedra, ...
            p_brain_inds, ...
            p_intended_source_inds, ...
            p_nearest_neighbour_inds, ...
            p_optimization_system_type ...
            );

    case { core.types.ZefSourceModel.StVenant, core.types.ZefSourceModel.ContinuousStVenant }

        [G, dipole_locations] = zef_st_venant_interpolation( ...
            p_nodes, ...
            p_tetrahedra, ...
            p_brain_inds, ...
            p_intended_source_inds, ...
            p_nearest_neighbour_inds, ...
            p_regparam ...
            );

    otherwise

        error("Unknown source model.");

end

end
