% --- Zeffiro documentation header ---
% function [G, dipole_locations] =  zef_lead_field_interpolation( ... — Builds or applies a sensor lead-field matrix for forward/inverse pipelines.
%
% Purpose:
%   Builds or applies a sensor lead-field matrix for forward/inverse pipelines.
%   Folder: Forward modeling: lead-field FEM assembly, DTI conductivity, NSE, wave models, and PCG solvers.
%
% Inputs:
%   p_nodes
%   p_tetrahedra
%   p_brain_inds
%   p_source_model
%   p_intended_source_inds
%   p_nearest_neighbour_inds
%   p_optimization_system_type
%   mustBeText
%   mustBeMember
%   p_regparam
%
% Calls (project):
%   core.types.ZefSourceModel.from
%   zef_hdiv_interpolation
%   zef_lead_field_interpolation
%   zef_st_venant_interpolation
%   zef_whitney_interpolation
%
% Workflow:
%   GUI: Used indirectly through tools, menus, or `zef_update` refresh chains.
%   Programmatic: `function [G, dipole_locations] =  zef_lead_field_interpolation( ...(p_nodes, p_tetrahedra, p_brain_inds, p_source_model, …)` with project root and `src` on the path.
% --- End Zeffiro documentation header
function [G, dipole_locations] =  zef_lead_field_interpolation( ...
    p_nodes, ...
    p_tetrahedra, ...
    p_brain_inds, ...
    p_source_model, ...
    p_intended_source_inds, ...
    p_nearest_neighbour_inds, ...
    p_optimization_system_type, ...
    p_regparam ...
    )

arguments
    p_nodes (:,3) double {mustBeNonNan}
    p_tetrahedra (:,4) double {mustBeInteger, mustBePositive}
    p_brain_inds (:,1) double {mustBeInteger, mustBePositive}
    p_source_model
    p_intended_source_inds (:,1) double {mustBeInteger, mustBePositive}
    p_nearest_neighbour_inds (:,1) double {mustBeInteger, mustBePositive}
    p_optimization_system_type { ...
        mustBeText, ...
        mustBeMember(p_optimization_system_type,{'pbo','mpo','none'}) ...
        }
    p_regparam (1,1) double
end

switch core.types.ZefSourceModel.from(p_source_model)

    case { core.types.ZefSourceModel.Whitney, core.types.ZefSourceModel.ContinuousWhitney }

        [G, dipole_locations] = zef_whitney_interpolation( ...
            p_nodes, ...
            p_tetrahedra, ...
            p_brain_inds, ...
            p_intended_source_inds, ...
            p_nearest_neighbour_inds, ...
            p_optimization_system_type ...
            );

    case { core.types.ZefSourceModel.Hdiv, core.types.ZefSourceModel.ContinuousHdiv }

        [G, dipole_locations] = zef_hdiv_interpolation( ...
            p_nodes, ...
            p_tetrahedra, ...
            p_brain_inds, ...
            p_intended_source_inds, ...
            p_nearest_neighbour_inds, ...
            p_optimization_system_type ...
            );

    case { core.types.ZefSourceModel.StVenant, core.types.ZefSourceModel.ContinuousStVenant }

        [G, dipole_locations] = zef_st_venant_interpolation( ...
            p_nodes, ...
            p_tetrahedra, ...
            p_brain_inds, ...
            p_intended_source_inds, ...
            p_nearest_neighbour_inds, ...
            p_regparam ...
            );

    otherwise

        error("Unknown source model.");

end

end
