classdef EnsureParpoolTest < matlab.unittest.TestCase
%ENSUREPARPOOLTEST  CPU parfor callers size a pool only through zef_ensure_parpool.

    methods (Test)
        function helperIsOnPath(testCase)
            testCase.verifyNotEmpty(which("zef_ensure_parpool"));
        end

        function cpuParallelCallersUseHelper(testCase)
            root = fileparts(which("zeffiro_interface"));
            testCase.assumeNotEmpty(root, "zeffiro_interface is not on the MATLAB path");
            files = [ ...
                fullfile(root, "src", "app", "zef_ensure_parpool.m"); ...
                fullfile(root, "src", "mesh", "zef_create_fem_mesh.m"); ...
                fullfile(root, "src", "forward", "lead_field", "zef_transfer_matrix.m"); ...
                fullfile(root, "src", "forward", "lead_field", "zef_lead_field_meg_fem.m"); ...
                fullfile(root, "src", "forward", "lead_field", "zef_lead_field_meg_grad_fem.m"); ...
                fullfile(root, "src", "forward", "lead_field", "zef_lead_field_eit_fem.m"); ...
                fullfile(root, "src", "forward", "wave", "make_born_approximation_amp.m"); ...
                fullfile(root, "src", "forward", "wave", "make_born_approximation_qam.m")];
            for k = 1:numel(files)
                src = fileread(files(k));
                testCase.verifyTrue(contains(src, "zef_ensure_parpool"), files(k));
            end
        end

        function megEitMeshTransferDoNotCallGcpDirectly(testCase)
            root = fileparts(which("zeffiro_interface"));
            testCase.assumeNotEmpty(root, "zeffiro_interface is not on the MATLAB path");
            files = [ ...
                fullfile(root, "src", "mesh", "zef_create_fem_mesh.m"); ...
                fullfile(root, "src", "forward", "lead_field", "zef_transfer_matrix.m"); ...
                fullfile(root, "src", "forward", "lead_field", "zef_lead_field_meg_fem.m"); ...
                fullfile(root, "src", "forward", "lead_field", "zef_lead_field_meg_grad_fem.m"); ...
                fullfile(root, "src", "forward", "lead_field", "zef_lead_field_eit_fem.m")];
            for k = 1:numel(files)
                src = fileread(files(k));
                testCase.verifyEmpty(regexp(src, '(?<![A-Za-z_])gcp\(', 'once'), files(k));
                testCase.verifyEmpty(regexp(src, '(?<![A-Za-z_])parpool\(', 'once'), files(k));
            end
        end
    end
end
