%ZEF_FIGURE_TOOL  Build the Figure tool (3-D axes and color/movie controls).
%
%   Zeffiro Interface.
%   Copyright © 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   Script (not a function). Not App Designer. Creates figure
%   "ZEFFIRO Interface: Figure tool" with uiaxes h_axes1. assignin
%   ('base','zef',zef) so string callbacks see the session. DeleteFcn
%   zef_reopen_figure. Layout is zef_figure_tool_layout.
%
%   See also zef_plot_volume, zef_set_figure_tool_sliders, zef_figure_tool_layout.

zef_ui_theme_local = zef_ui_theme(zef);

width_aux = 900;
height_aux = 720;
if isfield(zef, 'h_zeffiro_menu') && isvalid(zef.h_zeffiro_menu)
    ref = zef.h_zeffiro_menu.Position;
else
    ref = zef.segmentation_tool_default_position;
end
vertical_aux = ref(2) + ref(4) - height_aux;
horizontal_aux = ref(1) + ref(3) - width_aux;
zef.size_temp = [horizontal_aux vertical_aux width_aux height_aux];

zef.h_zeffiro = figure( ...
    'WindowStyle', 'normal', ...
    'PaperUnits', get(0, 'defaultfigurePaperUnits'), ...
    'Units', 'Pixels', ...
    'Position', zef.size_temp, ...
    'Renderer', get(0, 'defaultfigureRenderer'), ...
    'Visible', zef.use_display, ...
    'Color', zef_ui_theme_local.color.bg, ...
    'CloseRequestFcn', 'closereq;', ...
    'CurrentAxesMode', 'manual', ...
    'IntegerHandle', 'off', ...
    'NextPlot', get(0, 'defaultfigureNextPlot'), ...
    'Colormap', [0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0], ...
    'DoubleBuffer', 'off', ...
    'MenuBar', 'figure', ...
    'ToolBar', 'figure', ...
    'Name', 'ZEFFIRO Interface: Figure tool', ...
    'NumberTitle', 'off', ...
    'HandleVisibility', 'callback', ...
    'DeleteFcn', 'zef_reopen_figure;', ...
    'Tag', 'figure_tool', ...
    'UserData', [], ...
    'Resize', get(0, 'defaultfigureResize'), ...
    'PaperPosition', get(0, 'defaultfigurePaperPosition'), ...
    'PaperSize', [20.99999864 29.69999902], ...
    'PaperType', get(0, 'defaultfigurePaperType'), ...
    'InvertHardcopy', get(0, 'defaultfigureInvertHardcopy'), ...
    'ScreenPixelsPerInchMode', 'manual', ...
    'AutoResizeChildren', 'off');

try
    assignin('base', 'zef', zef);
catch
end

zef.h_zeffiro.ContextMenu = uicontextmenu(zef.h_zeffiro);
uimenu(zef.h_zeffiro.ContextMenu, 'Text', 'Axes pop-up', 'MenuSelectedFcn', 'zef_axes_popup;');

addToolbarExplorationButtons(zef.h_zeffiro);

zef.stop_movie = 0;
zef.h_axes1 = uiaxes('Parent', zef.h_zeffiro, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [20 200 500 400], 'Tag', 'axes1');
zef.h_axes1.Color = zef_ui_theme_local.color.axesBg;

zef.h_panel_sidebar = uipanel('Parent', zef.h_zeffiro, ...
    'Units', 'pixels', 'Position', [540 200 300 400], ...
    'Title', '', 'BorderType', 'line', ...
    'HighlightColor', zef_ui_theme_local.color.border, ...
    'ForegroundColor', zef_ui_theme_local.color.text, ...
    'BackgroundColor', zef_ui_theme_local.color.panel, ...
    'Tag', 'figure_sidebar');

zef.h_panel_lists = uipanel('Parent', zef.h_zeffiro, ...
    'Units', 'pixels', 'Position', [20 12 500 168], ...
    'Title', '', 'BorderType', 'line', ...
    'HighlightColor', zef_ui_theme_local.color.border, ...
    'ForegroundColor', zef_ui_theme_local.color.text, ...
    'BackgroundColor', zef_ui_theme_local.color.panel, ...
    'Tag', 'figure_lists');

sb = zef.h_panel_sidebar;
ls = zef.h_panel_lists;

uicontrol('Style', 'text', 'Parent', zef.h_zeffiro, 'Units', 'pixels', ...
    'String', '', 'HorizontalAlignment', 'left', 'Position', [20 600 240 20], ...
    'BackgroundColor', zef_ui_theme_local.color.bg, 'Tag', 'time_text', ...
    'Visible', 'off');

zef.h_toggle_controls = uicontrol('Tag', 'togglecontrolsbutton', 'UserData', 1, ...
    'Style', 'pushbutton', 'Parent', zef.h_zeffiro, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [540 570 140 28], 'String', 'Toggle controls', ...
    'Callback', 'zef_toggle_figure_controls;');
zef.h_toggle_edges = uicontrol('Tag', 'toggleedgesbutton', 'UserData', 1, ...
    'Style', 'pushbutton', 'Parent', sb, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [160 360 120 28], 'String', 'Toggle edges', ...
    'Callback', 'zef_toggle_edges;');

uicontrol('Tag', 'section_color', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Color', 'HorizontalAlignment', 'left', 'Position', [10 340 260 16]);
uicontrol('Tag', 'label_time', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Time', 'HorizontalAlignment', 'left', 'Position', [10 316 118 22]);
uicontrol('Tag', 'label_color_min', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Color min', 'HorizontalAlignment', 'left', 'Position', [10 292 118 22]);
uicontrol('Tag', 'label_color_max', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Color max', 'HorizontalAlignment', 'left', 'Position', [10 268 118 22]);
uicontrol('Tag', 'label_distance', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'View distance', 'HorizontalAlignment', 'left', 'Position', [10 244 118 22]);

zef.h_slider = uicontrol('Tag', 'slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 318 150 16], 'Min', 1e-6, 'Max', 1, 'Value', 1e-5, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'zef_slidding_callback;');
zef.h_colorscale_min_slider = uicontrol('Tag', 'colorscale_min_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 294 150 16], 'Min', -1, 'Max', 1, 'Value', 0, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.colorscale_min_slider = zef_update_colorscale_min; else; zef_update_colorscale_min(gcf); end;');
zef.h_colorscale_min_slider.UserData = zef.colorscale_min_slider;
zef.h_colorscale_max_slider = uicontrol('Tag', 'colorscale_max_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 270 150 16], 'Min', -1, 'Max', 1, 'Value', 0, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.colorscale_max_slider = zef_update_colorscale_max; else; zef_update_colorscale_max(gcf); end;');
zef.h_colorscale_max_slider.UserData = zef.colorscale_max_slider;
zef.h_update_zoom = uicontrol('Tag', 'update_zoom_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 246 150 16], 'Min', 0.1, 'Max', 100, 'Value', zef.update_zoom, 'Sliderstep', [0.001 0.001], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_zoom = zef_update_zoom; else; zef_update_zoom(gcf); end;');

uicontrol('Tag', 'section_transparency', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Transparency', 'HorizontalAlignment', 'left', 'Position', [10 222 260 16]);
uicontrol('Tag', 'label_transp_rec', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Reconstruction', 'HorizontalAlignment', 'left', 'Position', [10 198 118 22]);
uicontrol('Tag', 'label_transp_surf', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Surface', 'HorizontalAlignment', 'left', 'Position', [10 174 118 22]);
uicontrol('Tag', 'label_transp_sens', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Sensors', 'HorizontalAlignment', 'left', 'Position', [10 150 118 22]);
uicontrol('Tag', 'label_transp_cones', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Cones', 'HorizontalAlignment', 'left', 'Position', [10 126 118 22]);
uicontrol('Tag', 'label_transp_add', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Additional', 'HorizontalAlignment', 'left', 'Position', [10 102 118 22]);

zef.h_update_transparency_reconstruction = uicontrol('Tag', 'transparency_reconstruction_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 200 150 16], 'Min', 0, 'Max', 1, 'Value', zef.update_transparency_reconstruction, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_transparency_reconstruction = zef_update_transparency_reconstruction; else; zef_update_transparency_reconstruction(gcf); end;');
zef.h_update_transparency_surface = uicontrol('Tag', 'transparency_surface_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 176 150 16], 'Min', 0, 'Max', 1, 'Value', zef.update_transparency_surface, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_transparency_surface = zef_update_transparency_surface; else; zef_update_transparency_surface(gcf); end;');
zef.h_update_transparency_sensor = uicontrol('Tag', 'transparency_sensor_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 152 150 16], 'Min', 0, 'Max', 1, 'Value', zef.update_transparency_sensor, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_transparency_sensor = zef_update_transparency_sensor; else; zef_update_transparency_sensor(gcf); end;');
zef.h_update_transparency_cones = uicontrol('Tag', 'transparency_cones_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 128 150 16], 'Min', 0, 'Max', 1, 'Value', zef.update_transparency_cones, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_transparency_cones = zef_update_transparency_cones; else; zef_update_transparency_cones(gcf); end;');
zef.h_update_transparency_additional = uicontrol('Tag', 'transparency_additional_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 104 150 16], 'Min', 0, 'Max', 1, 'Value', zef.update_transparency_additional, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_transparency_additional = zef_update_transparency_additional; else; zef_update_transparency_additional(gcf); end;');

uicontrol('Tag', 'section_lighting', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Lighting', 'HorizontalAlignment', 'left', 'Position', [10 80 260 16]);
uicontrol('Tag', 'label_brightness', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Brightness', 'HorizontalAlignment', 'left', 'Position', [10 56 118 22]);
uicontrol('Tag', 'label_contrast', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Contrast', 'HorizontalAlignment', 'left', 'Position', [10 32 118 22]);
uicontrol('Tag', 'label_ambience', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Ambient', 'HorizontalAlignment', 'left', 'Position', [10 8 118 22]);
uicontrol('Tag', 'label_diffusion', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Diffuse', 'HorizontalAlignment', 'left', 'Position', [10 8 118 22]);
uicontrol('Tag', 'label_specular', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Specular', 'HorizontalAlignment', 'left', 'Position', [10 8 118 22]);

zef.h_update_brightness = uicontrol('Tag', 'update_brightness_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 58 150 16], 'Min', 0, 'Max', 5, 'Value', zef.update_brightness, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); [zef.update_contrast, zef.update_brightness] = zef_update_contrast_and_brightness; else; zef_update_contrast_and_brightness(gcf); end;');
zef.h_update_contrast = uicontrol('Tag', 'update_contrast_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 34 150 16], 'Min', -1, 'Max', 1, 'Value', zef.update_contrast, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); [zef.update_contrast, zef.update_brightness] = zef_update_contrast_and_brightness; else; zef_update_contrast_and_brightness(gcf); end;');
zef.h_update_ambience = uicontrol('Tag', 'update_ambience_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 10 150 16], 'Min', 0, 'Max', 1, 'Value', zef.update_ambience, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_ambience = zef_update_ambience; else; zef_update_ambience(gcf);end');
zef.h_update_diffusion = uicontrol('Tag', 'update_diffusion_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 10 150 16], 'Min', 0, 'Max', 1, 'Value', zef.update_diffusion, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_diffusion = zef_update_diffusion; else; zef_update_diffusion(gcf);end ');
zef.h_update_specular = uicontrol('Tag', 'update_specular_slider', 'Style', 'slider', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 10 150 16], 'Min', 0, 'Max', 1, 'Value', zef.update_specular, 'Sliderstep', [0.01 0.01], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_specular = zef_update_specular; else; zef_update_specular(gcf);end');

uicontrol('Tag', 'section_appearance', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Appearance', 'HorizontalAlignment', 'left', 'Position', [10 8 260 16]);
uicontrol('Tag', 'label_lights', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Lights', 'HorizontalAlignment', 'left', 'Position', [10 8 118 22]);
uicontrol('Tag', 'label_colormap', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Colormap', 'HorizontalAlignment', 'left', 'Position', [10 8 118 22]);
uicontrol('Tag', 'label_scale', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Scale', 'HorizontalAlignment', 'left', 'Position', [10 8 118 22]);

zef.h_update_lights = uicontrol('Tag', 'lightsselection', 'Style', 'popupmenu', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 8 150 22], 'String', {'Default', 'Lights off', 'Add X', 'Add Y', 'Add Z', 'Headlight'}, ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_lights = zef_update_lights; else; zef.update_lights = zef_update_lights(gcf);end');
zef.h_update_colormap = uicontrol('Tag', 'colormapselection', 'Style', 'popupmenu', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 8 150 22], 'String', zef.colormap_items, 'Value', zef.update_colormap, ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_colormap = zef.h_update_colormap.Value; end; zef_update_contrast_and_brightness(gcf);');
zef.h_update_colorscale = uicontrol('Tag', 'colorscaleselection', 'Style', 'popupmenu', 'Parent', sb, 'Units', 'pixels', ...
    'Position', [130 8 150 22], 'String', {'Linear', 'Logarithmic'}, 'Value', zef.update_colorscale, ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.update_colorscale = zef_update_colorscale; else; zef_update_colorscale(gcf); end;');

uicontrol('Tag', 'label_loop', 'Style', 'text', 'Parent', sb, 'Units', 'pixels', ...
    'String', 'Loop', 'HorizontalAlignment', 'left', 'Position', [10 40 44 22]);
zef.h_loop_movie = uicontrol('Style', 'Checkbox', 'Parent', sb, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [58 42 22 18], ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.loop_movie = get(gcbo,''value''); end;  set(gcbo,''UserData'',get(gcbo,''value''));', ...
    'HorizontalAlignment', 'left', 'Tag', 'loop_movie');
zef.h_loop_movie_count = uicontrol('Style', 'Edit', 'Parent', sb, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [84 40 48 22], 'String', 'Loop visualization', ...
    'Callback', 'if isequal(get(gca,''Parent''), zef.h_zeffiro); zef.loop_movie_count = str2num(get(gcbo,''string'')); end; set(gcbo,''UserData'',str2num(get(gcbo,''string'')));', ...
    'HorizontalAlignment', 'right', 'Tag', 'loop_count');

zef.h_reset_figure_tool_sliders = uicontrol('Style', 'togglebutton', 'Parent', sb, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [10 8 65 28], 'String', 'Reset', 'Tag', 'resetbutton', ...
    'Callback', 'zef = zef_set_figure_tool_sliders(zef,0);zef.h_reset_figure_tool_sliders.Value=0;');
zef.h_play_movie = uicontrol('Style', 'pushbutton', 'Parent', sb, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [80 8 65 28], 'String', 'Play', 'Tag', 'playbutton', ...
    'Callback', 'zef_play_cdata(max(1,double(get(findall(gcf,''Tag'',''loop_movie''),''UserData''))*get(findall(gcf,''Tag'',''loop_count''),''UserData'')));');
zef.h_stop_movie = uicontrol('Style', 'togglebutton', 'Parent', sb, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [150 8 65 28], 'String', 'Stop', 'Tag', 'stopbutton', ...
    'Callback', @zef_callbackstop);
zef.h_logoplot = uicontrol('Style', 'pushbutton', 'Parent', sb, 'Visible', 'on', 'Units', 'pixels', ...
    'Position', [220 8 65 28], 'String', 'Logo', 'Tag', 'logobutton', ...
    'Callback', @zef_logoplot);

set(zef.h_loop_movie_count, 'String', num2str(zef.loop_movie_count));

zef.h_compartment_visible_color = zef_colored_list('create', ls, ...
    [10 28 150 110], 'compartment_visible_color', ...
    'Callback', 'zef_set_compartment_color; zef_update;', ...
    'Multiselect', false, ...
    'Trigger', 'buttondown');
zef.h_sensor_visible_color = zef_colored_list('create', ls, ...
    [170 28 150 110], 'sensor_visible_color', ...
    'Callback', 'zef_set_sensor_color; zef_update;', ...
    'Multiselect', true, ...
    'Trigger', 'buttondown');
zef.h_system_information = zef_colored_list('create', ls, ...
    [330 28 150 110], 'system_information', ...
    'ShowSwatches', false);

uicontrol('Parent', ls, 'Units', 'pixels', 'HorizontalAlignment', 'left', ...
    'String', 'Compartments', 'Style', 'text', 'Position', [10 140 150 18], ...
    'Tag', 'label_compartments', 'BackgroundColor', zef_ui_theme_local.color.panel);
uicontrol('Parent', ls, 'Units', 'pixels', 'HorizontalAlignment', 'left', ...
    'String', 'Sensors', 'Style', 'text', 'Position', [170 140 150 18], ...
    'Tag', 'label_sensors', 'BackgroundColor', zef_ui_theme_local.color.panel);
uicontrol('Parent', ls, 'Units', 'pixels', 'HorizontalAlignment', 'left', ...
    'String', 'Details', 'Style', 'text', 'Position', [330 140 150 18], ...
    'Tag', 'label_details', 'BackgroundColor', zef_ui_theme_local.color.panel);
uicontrol('Style', 'text', 'Parent', ls, 'Units', 'pixels', ...
    'String', 'Copyright © 2018– Sampsa Pursiainen & ZI Development Team', ...
    'HorizontalAlignment', 'left', 'Position', [10 4 470 16], 'Tag', 'copyright_text', ...
    'BackgroundColor', zef_ui_theme_local.color.panel);

zef = zef_update_fig_details(zef);

set(zef.h_zeffiro, 'HandleVisibility', 'on');
set(zef.h_zeffiro, 'WindowButtonDownFcn', 'zef.h_zeffiro = zef.h_zeffiro; zef.h_axes1 = zef_ui_axes(zef.h_zeffiro);');

zef.h_zeffiro.GraphicsSmoothing = 'off';

h_loop_count = findall(zef.h_zeffiro, 'Tag', 'loop_count');
if ~isempty(h_loop_count)
    loop_str = get(h_loop_count(1), 'String');
    if iscell(loop_str)
        loop_str = loop_str{1};
    end
    set(h_loop_count(1), 'UserData', str2double(loop_str));
end
h_loop_movie = findall(zef.h_zeffiro, 'Tag', 'loop_movie');
if ~isempty(h_loop_movie)
    set(h_loop_movie(1), 'UserData', get(h_loop_movie(1), 'Value'));
end

set(zef.h_zeffiro, 'PaperPosition', [0 0 zef.snapshot_horizontal_resolution / 200 zef.snapshot_vertical_resolution / 200]);
set(zef.h_zeffiro, 'PaperSize', [zef.snapshot_vertical_resolution / 200 zef.snapshot_horizontal_resolution / 200]);

if zef.clear_axes1
    zef.h_colorbar = findobj(zef.h_zeffiro, 'Tag', 'Colorbar');
    if ~isempty(zef.h_colorbar)
        colorbar(zef.h_colorbar, 'delete');
    end
else
    zef.clear_axes1 = 1;
end

if isfield(zef, 'zeffiro_current_size')
    if ~iscell(zef.zeffiro_current_size)
        zef = rmfield(zef, 'zeffiro_current_size');
    end
end

set(zef.h_zeffiro, 'Name', [get(zef.h_zeffiro, 'Name') ' ' num2str(zef_fig_num)]);

if ~ismember('ZefFig', properties(zef.h_zeffiro))
    addprop(zef.h_zeffiro, 'ZefFig');
end
set(zef.h_zeffiro, 'ZefFig', zef_fig_num);

zef.h_zeffiro.SizeChangedFcn = @(src, evt) zef_figure_tool_layout(src);
zef_ui_apply_size(zef.h_zeffiro, 900, 720, 760, 580);
zef_figure_tool_layout(zef.h_zeffiro);
zef_ui_apply_theme(zef.h_zeffiro, zef_ui_theme_local);

zef = rmfield(zef, 'size_temp');
clear zef_ui_theme_local sb ls;

zef_logoplot;

zef.h_zeffiro.Visible = zef.use_display;
zef_window_manager('standalone', zef.h_zeffiro);

try
    assignin('base', 'zef', zef);
catch
end

zef.h_axes1.Units = 'pixels';
drawnow;
pause(0.001);
zef_figure_tool_layout(zef.h_zeffiro);

function zef_logoplot(o, e, h) %#ok<INUSD>

if nargin == 0
    h_axes = evalin('caller', 'zef.h_axes1');
else
    h_fig = ancestor(o, 'figure');
    h_axes = zef_ui_axes(h_fig);
end
if isempty(h_axes) || ~isvalid(h_axes(1))
    return
end
h_axes = h_axes(1);

bg = [0.970 0.975 0.978];
try
    th = zef_ui_theme();
    bg = th.color.bg;
catch
end

img = [];
try
    img = local_logo_image(bg);
catch
    try
        img = imread('zeffiro_interface_compass.png', 'BackgroundColor', bg);
    catch
    end
end
if isempty(img)
    return
end

cla(h_axes, 'reset');
h_axes.Tag = 'axes1';
image(h_axes, img);
axis(h_axes, 'image');
h_axes.YDir = 'reverse';
h_axes.XTick = [];
h_axes.YTick = [];
h_axes.Box = 'off';
h_axes.Color = bg;
try
    h_axes.XColor = 'none';
    h_axes.YColor = 'none';
catch
end
try
    disableDefaultInteractivity(h_axes);
catch
end
try
    h_axes.Toolbar = [];
catch
    try
        h_axes.Toolbar.Visible = 'off';
    catch
    end
end
h_axes.Visible = 'on';
try
    tt = findall(ancestor(h_axes, 'figure'), 'Tag', 'time_text');
    if ~isempty(tt) && isvalid(tt(1))
        set(tt(1), 'String', '', 'Visible', 'off');
    end
catch
end
try
    delete(h_axes.Legend);
    delete(h_axes.XLabel);
    delete(h_axes.YLabel);
    delete(h_axes.ZLabel);
catch
end

try
    zef_figure_tool_layout(ancestor(h_axes, 'figure'));
catch
end
h_axes.Tag = 'axes1';

end

function img = local_logo_image(bg)

fname = 'zeffiro_interface_compass.png';
alpha = [];
try
    [img, ~, alpha] = imread(fname);
catch
    img = imread(fname, 'BackgroundColor', bg);
end
if size(img, 3) == 1
    img = repmat(img, [1 1 3]);
end
if ~isempty(alpha)
    a = im2double(alpha);
    if size(a, 3) > 1
        a = a(:, :, 1);
    end
    bg8 = reshape(double(uint8(max(0, min(255, round(255 * bg))))), 1, 1, 3);
    img = uint8(double(img) .* a + bg8 .* (1 - a));
end
tol = 14;
bg8 = reshape(double(uint8(max(0, min(255, round(255 * bg))))), 1, 1, 3);
mask = max(abs(double(img) - bg8), [], 3) > tol;
white = max(abs(double(img) - 255), [], 3) < 8;
mask = mask & ~white;
if ~any(mask(:))
    return
end
[r, c] = find(mask);
pad = 12;
r1 = max(1, min(r) - pad);
r2 = min(size(img, 1), max(r) + pad);
c1 = max(1, min(c) - pad);
c2 = min(size(img, 2), max(c) + pad);
img = img(r1:r2, c1:c2, :);
bg8 = uint8(max(0, min(255, round(255 * bg))));
near_white = max(abs(double(img) - 255), [], 3) < 28;
for k = 1:size(img, 3)
    ch = img(:, :, k);
    ch(near_white) = bg8(k);
    img(:, :, k) = ch;
end

end
