function zef = zef_ramus_class_window(zef)
%ZEF_RAMUS_CLASS_WINDOW  Build the RAMUS class-inverter dialog.
%
%   Zeffiro Interface.
%   Copyright 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   See also zef_ramus_class_start, zef_open_class_inverse, inverse.RAMUSInverter.

if nargin == 0
    zef = evalin('base', 'zef');
end

spec = struct();
spec.method_id = "ramus";
spec.title = 'RAMUS';
spec.method_fields = { ...
    struct('name', 'method_type', 'label', 'Post-hoc weighting', ...
        'kind', 'dropdown', 'value', 'None', ...
        'items', {{'None', 'sLORETA each step', 'sLORETA last step', ...
            'dSPM each step', 'dSPM last step'}}, 'scope', 'method'), ...
    struct('name', 'hyperprior', 'label', 'Hyperprior', ...
        'kind', 'dropdown', 'value', 'Inverse gamma', ...
        'items', {{'Inverse gamma', 'Gamma'}}, 'scope', 'method'), ...
    struct('name', 'hyperprior_mode', 'label', 'Hyperprior mode', ...
        'kind', 'dropdown', 'value', 'Constant', ...
        'items', {{'Constant', 'Balanced'}}, 'scope', 'method'), ...
    struct('name', 'n_map_iterations', 'label', 'MAP iterations', ...
        'kind', 'numeric', 'value', 10, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'number_of_multiresolution_levels', 'label', 'Multiresolution levels', ...
        'kind', 'numeric', 'value', 3, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'sparsity_factor', 'label', 'Sparsity factor', ...
        'kind', 'numeric', 'value', 10, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'number_of_decompositions', 'label', 'Decompositions', ...
        'kind', 'numeric', 'value', 20, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'hyperprior_tail_length_db', 'label', 'Hyperprior tail length (dB)', ...
        'kind', 'numeric', 'value', 10, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'hyperprior_weight', 'label', 'Hyperprior weight', ...
        'kind', 'numeric', 'value', 0, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'amplitude_db', 'label', 'Amplitude (dB)', ...
        'kind', 'numeric', 'value', 20, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'prior_over_measurement_db', 'label', 'Prior over measurement (dB)', ...
        'kind', 'numeric', 'value', 20, 'items', {{}}, 'scope', 'method')};

zef = zef_open_class_inverse(zef, spec);

end
