function zef = zef_ukfnmm_window(zef)
%ZEF_UKFNMM_WINDOW  Build the UKF-NMM class-inverter dialog.
%
%   Zeffiro Interface.
%   Copyright © 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   See also zef_ukfnmm_start, zef_open_class_inverse.

if nargin == 0
    zef = evalin('base', 'zef');
end

spec = struct();
spec.method_id = "ukfnmm";
spec.title = 'UKF-NMM';
spec.method_fields = { ...
    struct('name', 'number_of_corrclusters', 'label', 'Correlation clusters', ...
        'kind', 'numeric', 'value', 3, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'score_threshold', 'label', 'Score threshold', ...
        'kind', 'numeric', 'value', 0.2, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'alpha', 'label', 'UKF α', ...
        'kind', 'numeric', 'value', 1, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'kappa', 'label', 'UKF κ', ...
        'kind', 'numeric', 'value', 0, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'beta', 'label', 'UKF β', ...
        'kind', 'numeric', 'value', 2, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'evolution_prior_model', 'label', 'Evolution prior', ...
        'kind', 'dropdown', 'value', 'Sensitivity scaling', ...
        'items', {{'Sensitivity scaling', 'Avg. sensit. scaling', 'SVD-based', ...
            'Avg. SVD-based', 'Reworked original', 'User supplied Q'}}, ...
        'scope', 'method'), ...
    struct('name', 'smoother_type', 'label', 'Spatial smoother', ...
        'kind', 'dropdown', 'value', 'None', ...
        'items', {{'None', 'RTS', 'Sample RTS'}}, 'scope', 'method'), ...
    struct('name', 'evolution_prior_db', 'label', 'Evolution prior (dB)', ...
        'kind', 'numeric', 'value', 0, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'initial_prior_steering_db', 'label', 'Initial prior steering (dB)', ...
        'kind', 'numeric', 'value', 0, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'number_of_noise_steps', 'label', 'Noise-only frames', ...
        'kind', 'numeric', 'value', 4, 'items', {{}}, 'scope', 'method')};

zef = zef_open_class_inverse(zef, spec);

end
