function zef = zef_beamformer_class_window(zef)
%ZEF_BEAMFORMER_CLASS_WINDOW  Build the Beamformer class-inverter dialog.
%
%   Zeffiro Interface.
%   Copyright 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   See also zef_beamformer_class_start, zef_open_class_inverse, inverse.BeamformerInverter.

if nargin == 0
    zef = evalin('base', 'zef');
end

spec = struct();
spec.method_id = "beamformer";
spec.title = 'Beamformer';
spec.method_fields = { ...
    struct('name', 'method_type', 'label', 'Beamformer type', ...
        'kind', 'dropdown', 'value', ...
        'Linearly constrained minimum variance (LCMV) beamformer', ...
        'items', {{'Linearly constrained minimum variance (LCMV) beamformer', ...
            'Unit noise gain (UNG) beamformer', ...
            'Unit-gain constrained beamformer'}}, ...
        'scope', 'method'), ...
    struct('name', 'cov_reg_parameter', 'label', 'Covariance regularization', ...
        'kind', 'numeric', 'value', 0.05, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'leadfield_reg_parameter', 'label', 'Leadfield regularization', ...
        'kind', 'numeric', 'value', 0.001, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'leadfield_reg_type', 'label', 'Leadfield regularization type', ...
        'kind', 'dropdown', 'value', 'Basic', ...
        'items', {{'Basic', 'Pseudoinverse'}}, 'scope', 'method'), ...
    struct('name', 'leadfield_normalization', 'label', 'Leadfield normalization', ...
        'kind', 'dropdown', 'value', 'None', ...
        'items', {{'None', 'Matrix norm', 'Column norm', 'Row norm'}}, ...
        'scope', 'method')};

zef = zef_open_class_inverse(zef, spec);

end
