function zef = zef_grouplasso_window(zef)
%ZEF_GROUPLASSO_WINDOW  Build the Group Lasso class-inverter dialog.
%
%   Zeffiro Interface.
%   Copyright © 2018- Sampsa Pursiainen & ZI Development Team
%   See: https://github.com/sampsapursiainen/zeffiro_interface
%   Licensed under the GNU General Public License v3.0 (see LICENSE).
%
%   See also zef_grouplasso_start, zef_open_class_inverse.

if nargin == 0
    zef = evalin('base', 'zef');
end

spec = struct();
spec.method_id = "grouplasso";
spec.title = 'Group Lasso';
spec.method_fields = { ...
    struct('name', 'estimation_type', 'label', 'Estimation type', ...
        'kind', 'dropdown', 'value', 'IAS', ...
        'items', {{'IAS', 'EM', 'Standardized'}}, 'scope', 'method'), ...
    struct('name', 'hyperprior_mode', 'label', 'Hyperprior', ...
        'kind', 'dropdown', 'value', 'Sensitivity weighted', ...
        'items', {{'Sensitivity weighted', 'Manually selected'}}, 'scope', 'method'), ...
    struct('name', 'beta', 'label', 'β', ...
        'kind', 'numeric', 'value', 3, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'theta0', 'label', 'θ₀', ...
        'kind', 'numeric', 'value', 1e-10, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'n_map_iterations', 'label', 'MAP iterations', ...
        'kind', 'numeric', 'value', 25, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'n_L1_iterations', 'label', 'L1 iterations', ...
        'kind', 'numeric', 'value', 5, 'items', {{}}, 'scope', 'method'), ...
    struct('name', 'initial_prior_steering_db', 'label', 'Initial prior steering (dB)', ...
        'kind', 'numeric', 'value', 0, 'items', {{}}, 'scope', 'method')};

zef = zef_open_class_inverse(zef, spec);

end
